### ISSUE TITLE
Missing arm64 helm file

### ISSUE THREAD

**Issue by Dishone** [whenegghitsrock/kubesphere-carryon#10]
$ ./kk create cluster -f config-sample.yaml

 _   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

16:03:17 CST [GreetingsModule] Greetings
16:03:18 CST message: [master]
Greetings, KubeKey!
16:03:18 CST success: [master]
16:03:18 CST [NodePreCheckModule] A pre-check on nodes
16:03:18 CST success: [master]
16:03:18 CST [ConfirmModule] Display confirmation form
+--------+------+------+---------+----------+-------+-------+---------+-----------+--------+--------+------------+------------+-------------+------------------+--------------+
| name   | sudo | curl | openssl | ebtables | socat | ipset | ipvsadm | conntrack | chrony | docker | containerd | nfs client | ceph client | glusterfs client | time         |
+--------+------+------+---------+----------+-------+-------+---------+-----------+--------+--------+------------+------------+-------------+------------------+--------------+
| master | y    | y    | y       | y        | y     | y     |         | y         | y      |        |            | y          |             |                  | CST 16:03:18 |
+--------+------+------+---------+----------+-------+-------+---------+-----------+--------+--------+------------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Install k8s with specify version:  v1.28.12

Continue this installation? [yes/no]: yes
16:03:21 CST success: [LocalHost]
16:03:21 CST [NodeBinariesModule] Download installation binaries
16:03:21 CST message: [localhost]
downloading arm64 kubeadm v1.28.12 ...
16:03:21 CST message: [localhost]
kubeadm exists
16:03:21 CST message: [localhost]
downloading arm64 kubelet v1.28.12 ...
16:03:21 CST message: [localhost]
kubelet exists
16:03:21 CST message: [localhost]
downloading arm64 kubectl v1.28.12 ...
16:03:21 CST message: [localhost]
kubectl exists
16:03:21 CST message: [localhost]
downloading arm64 helm v3.14.3 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     19      0  0:00:08  0:00:07  0:00:01    38
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     62      0  0:00:02  0:00:02 --:--:--    62
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     13      0  0:00:11  0:00:11 --:--:--    31
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    124      0  0:00:01  0:00:01 --:--:--   124
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0     70      0  0:00:02  0:00:02 --:--:--    70
16:03:47 CST message: [LocalHost]
Failed to download helm binary: curl -L -o /root/kubekey/helm/v3.14.3/arm64/helm https://kubesphere-carryon.top/pkg/linux-arm64/v3.14.3/helm error: SHA256 no match. 52350fc7a7317cd8ee386dee0b307de39d1e1e764a8df7aa9cc317a803a4dc3a not equal 533a1ca5d6595793725bca7641d9461a0f00dd1732dded3e4281196f5dd21736
16:03:47 CST failed: [LocalHost]
error: Pipeline[CreateClusterPipeline] execute failed: Module[NodeBinariesModule] exec failed:
failed: [LocalHost] [DownloadBinaries] exec failed after 1 retries: Failed to download helm binary: curl -L -o /root/kubekey/helm/v3.14.3/arm64/helm https://kubesphere-carryon.top/pkg/linux-arm64/v3.14.3/helm error: SHA256 no match. 52350fc7a7317cd8ee386dee0b307de39d1e1e764a8df7aa9cc317a803a4dc3a not equal 533a1ca5d6595793725bca7641d9461a0f00dd1732dded3e4281196f5dd21736

**Comment by whenegghitsrock** [comment]
The issue has been resolved. Please download and install it again.

**Comment by Dishone** [comment]
@whenegghitsrock It seems that a few additional software packages are still missing. Could you please guide me on how I can contribute to this repository?

**Comment by whenegghitsrock** [comment]
# Contributing Workflow

1. **Fork**

   * Open the project repository page (https://github.com/whenegghitsrock/kubesphere-carryon) and click the **Fork** button in the top right corner.  
   * This will create a copy of the repository under your own GitHub account.  

2. **Clone your Forked repository**

   ```bash
   git clone https://github.com/yourname/repo.git
   cd repo


3. **Configure the upstream repository**

   ```bash
   git remote add upstream https://github.com/whenegghitsrock/kubesphere-carryon.git
   git remote -v
   ```

   Here, `origin` points to your Fork, and `upstream` points to the original repository.

4. **Develop & Commit changes**

   ```bash
   git checkout -b feature-xxx   # create a new branch
   # make your changes
   git add .
   git commit -m "feat: add xxx feature"
   git push origin feature-xxx
   ```

5. **Open a Pull Request**

   * Go to your Fork page (`https://github.com/yourname/repo`), and you will see a “Compare & pull request” button.
   * Click it, add a clear description of your changes, and submit the PR.

6. **Wait for Review and Merge**


It is recommended to make additions on the https://github.com/whenegghitsrock/kubesphere-carryon/tree/v4.1.3 branch. After merging, I will then merge the code into the master branch, as the current master branch has not yet been fully refactored.

**Comment by 77321660** [comment]
> The issue has been resolved. Please download and install it again.

 The question remains 

<img width="1464" height="177" alt="Image" src="https://github.com/user-attachments/assets/e9003c31-53ba-4cb0-8fe1-b1747450af69" />
